### ISSUE TITLE
Cursor not centered in KDE

### ISSUE THREAD

**Issue by Ondra3211** [BoyOrigin/glfw-wayland#1]
Hi, I tried your patch with the cursor but it doesn't work on KDE.
When I open inventory the block in the middle is actually hovered but cursor isn't there.
I tested this on Hyprland it works fine there. Maybe some kwin problem?

![mc wayland cursor](https://github.com/BoyOrigin/glfw-wayland/assets/39314277/3702b5c9-9fd6-42ec-b5da-c8799139be53)

**Comment by LeaPhant** [comment]
Seems like this has been fixed, works for me after https://github.com/BoyOrigin/glfw-wayland/commit/86eacdc9e70ef4b63dff8fe58042831bd50e6bb7.
