### ISSUE TITLE
unable to launch minecraft.

### ISSUE THREAD

**Issue by zeak-z** [BoyOrigin/glfw-wayland#4]
GLFW error 65544: EGL: Failed to clear current context: An EGLDisplay argument does not name a valid EGL display connection.

Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

Launcher: MultiMC 0.7.0

Minecraft Version: 1.20.1

NVIDIA Drivers: 550.54.14-5 DKMS Patch

Window Manager: Sway

OS: Endeavor OS Kernel 6.7.9

**Comment by minerscale** [comment]
I was able to fix it with the environment variable `__GL_THREADED_OPTIMIZATIONS` set to `0`.

**Comment by zeak-z** [comment]
> I was able to fix it with the environment variable `__GL_THREADED_OPTIMIZATIONS` set to `0`.

thank you, this fixed it!

**Comment by nojvspine** [comment]
with `__GL_THREADED_OPTIMIZATIONS=0` minecraft starts but freezes immediately

Launcher: PrismLauncher 9.2
Version: Forge 1.19.2
NVIDIA Drivers: 565.77-3 dkms
WM: Hyprland
OS: Arch Linux
Kernel: 6.12.10.arch1-1
Modlist: 
[mods.md](https://github.com/user-attachments/files/18516090/mods.md)

**Comment by McSnurtle** [comment]
> with `__GL_THREADED_OPTIMIZATIONS=0` minecraft starts but freezes immediately
> 
> Launcher: PrismLauncher 9.2 Version: Forge 1.19.2 NVIDIA Drivers: 565.77-3 dkms WM: Hyprland OS: Arch Linux Kernel: 6.12.10.arch1-1 Modlist: [mods.md](https://github.com/user-attachments/files/18516090/mods.md)

I know this is old, but if you're still having this issue it is likely caused by your mods. Regardless, you'd best make a seperate issue to get help with this. I can personally recommend are trying to boot the game in vanilla to confirm it isn't that.

Enjoy the day!
