### ISSUE TITLE
Unable to launch Minecraft version 1.20.1

### ISSUE THREAD

**Issue by drshapeless** [BoyOrigin/glfw-wayland#7]
When running minecraft 1.20.1, it gives the following error.

GLFW error 65548: Wayland: The platform does not support setting the window icon.

However, running minecraft 1.20.4 is completely fine.

I am using the lastest HEAD version of this repo and upstream glfw-3.5

**Comment by drshapeless** [comment]
This is fixed by using the mod WayGL and changing the LWJGL to version 3.3.2.

**Comment by kamild1996** [comment]
I'm having this issue currently, except I can't use WayGL because I'm playing a 1.20.1 Forge modpack and not a Fabric one (WayGL is only available on [Neo]Forge starting from MC 1.21), and changing the LWJGL version to 3.3.2 did not help.
